export const STUDENT_EXAMSGIVEN_REQUEST = 'STUDENT_EXAMSGIVEN_REQUEST'
export const STUDENT_EXAMSGIVEN_SUCEESS = 'STUDENT_EXAMSGIVEN_SUCEESS'
export const STUDENT_EXAMSGIVEN_FAIL = 'STUDENT_EXAMSGIVEN_FAIL'
